### ISSUE TITLE
Enable Go mod to be executed as part of the hugo process for dependency installation

### ISSUE THREAD

**Issue by Ryank90** [Ryank90/alpine-hugo-firebase#10]
Enable Go mod to be executed as part of the hugo process for dependency installation.

**Comment by Ryank90** [comment]
Resolved in the hugo deployment repository itself by using:

```
- uses: actions/checkout@v4
   with:
       submodules: recursive
       fetch-depth: 0
```

Within the .github workflow.
